# src/main/resources/application.yml
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: settlement-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:sporty
    driver-class-name: org.h2.Driver
    username: sporty
    password: 1234
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      # TODO: This should be set to `none` or `validate` in PRODUCTION
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
